name: Publish VS Code Extension

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies (Yarn)
        run: yarn install

      - name: Package extension (Yarn)
        run: yarn run vsce package --yarn

      - name: Publish extension (Yarn)
        run: yarn run vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --yarn
